format = '''
$username$directory$git_branch$custom$rust$python
$character'''

palette = 'colors'

[palettes.colors]
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[username]
show_always = true
style_user = "color3 bold"
style_root = "red bold"
format = "[$user: ]($style)"
disabled = false

# Prompt symbols 
[character]
success_symbol = "[â¯](color9 bold)"
error_symbol = "[â¯](bold red)"
# vi stuff
vicmd_symbol = "[â®](bold color5)"
vimcmd_visual_symbol = "[â®](bold purple)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_replace_one_symbol = "[â®](bold purple)"

[directory]
format = "[$path]($style)> "
read_only = "[R]"
read_only_style = "bold red"
truncation_length = 0

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
disabled = false

[shell]
bash_indicator = "bsh"
zsh_indicator = "zsh"
fish_indicator = ''
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = true

# When ranger shell is used. With multiple levels, if one ranger shell is open inside another.
[custom.ranger]
command = """
if test $RANGER_LEVEL -eq 1
    echo 'î«¬ ranger'
else if test $RANGER_LEVEL -gt 1
    echo 'î«¬ ranger~'$RANGER_LEVEL
end
"""
when = "test $RANGER_LEVEL -ge 1"
#format = "[$output]($style)"
#format = "ğŸ¯ [$symbol]($style) "
style = "bold color8"


[time]
format = "[î‚¶](fg:color8 bg:color4)[ïº ](bg:color8 fg:color5)[î‚´](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[î‚´](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[î‚¶](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[î‚´](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[î‚´](fg:color4) "
symbol = 'ğŸ'
# pyenv_version_name = true
pyenv_prefix = 'venv'
